/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package de.damaico.brick.visualizer;

import com.tinkerforge.Device;
import java.awt.Point;
import java.awt.datatransfer.Transferable;
import java.beans.BeanInfo;
import org.netbeans.api.settings.ConvertAsProperties;
import org.netbeans.api.visual.action.AcceptProvider;
import org.netbeans.api.visual.action.ActionFactory;
import org.netbeans.api.visual.action.ConnectorState;
import org.netbeans.api.visual.widget.LabelWidget;
import org.netbeans.api.visual.widget.LayerWidget;
import org.netbeans.api.visual.widget.Scene;
import org.netbeans.api.visual.widget.Widget;
import org.netbeans.api.visual.widget.general.IconNodeWidget;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.nodes.Node;
import org.openide.nodes.NodeTransfer;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
    dtd = "-//de.damaico.brick.visualizer//BrickVisualizer//EN",
autostore = false)
@TopComponent.Description(
    preferredID = "BrickVisualizerTopComponent",
//iconBase="SET/PATH/TO/ICON/HERE", 
persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "output", openAtStartup = true)
@ActionID(category = "Window", id = "de.damaico.brick.visualizer.BrickVisualizerTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
    displayName = "#CTL_BrickVisualizerAction",
preferredID = "BrickVisualizerTopComponent")
@Messages({
    "CTL_BrickVisualizerAction=BrickVisualizer",
    "CTL_BrickVisualizerTopComponent=BrickVisualizer Window",
    "HINT_BrickVisualizerTopComponent=This is a BrickVisualizer window"
})
public final class BrickVisualizerTopComponent extends TopComponent {

    public BrickVisualizerTopComponent() {
        initComponents();
        setName(Bundle.CTL_BrickVisualizerTopComponent());
        setToolTipText(Bundle.HINT_BrickVisualizerTopComponent());

        // create scene
        final Scene scene = new Scene();

        // add baseLayer to scene
        final LayerWidget baseLayer = new LayerWidget(scene);
        scene.addChild(baseLayer);


        // make the scene accept things
        scene.getActions().addAction(ActionFactory.createAcceptAction(new AcceptProvider() {
            @Override
            public ConnectorState isAcceptable(Widget widget, Point point, Transferable t) {
                return ConnectorState.ACCEPT;
            }

            @Override
            public void accept(Widget widget, Point point, Transferable t) {
                Node node = NodeTransfer.node(t, NodeTransfer.DND_COPY_OR_MOVE);
                if (node != null) {
                    Device device = node.getLookup().lookup(Device.class);

                    if (device != null) {
                        IconNodeWidget simpleWidget;
                        simpleWidget = new IconNodeWidget(scene);
                        simpleWidget.setLabel(device.getClass().toString());
                        simpleWidget.setImage(node.getIcon(BeanInfo.ICON_COLOR_16x16));
                        simpleWidget.setPreferredLocation(point);
                        simpleWidget.getActions().addAction(ActionFactory.createMoveAction());
                        baseLayer.addChild(simpleWidget);
                    } else {
                        // add hello world widget to baseLayer and make it moveable
                        LabelWidget helloWorldWidget = new LabelWidget(scene, "Nope!");
                        helloWorldWidget.setPreferredLocation(point);
                        helloWorldWidget.getActions().addAction(ActionFactory.createMoveAction());
                        baseLayer.addChild(helloWorldWidget);
                    }
                }
            }
        }));

        // add it to our scrollpane
        jScrollPane1.setViewportView(scene.createView());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
